//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.27 at 09:49:14 AM COT 
//


package com.nequi.uts601.messaging.services.protectedmsg;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nequi.uts601.messaging.services.protectedmsg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProtectedMsgRQ_QNAME = new QName("http://nequi.co/message/bussines/services/protectedMsgService", "protectedMsgRQ");
    private final static QName _ProtectedMsgRS_QNAME = new QName("http://nequi.co/message/bussines/services/protectedMsgService", "protectedMsgRS");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nequi.uts601.messaging.services.protectedmsg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProtectedMsgRSType }
     * 
     */
    public ProtectedMsgRSType createProtectedMsgRSType() {
        return new ProtectedMsgRSType();
    }

    /**
     * Create an instance of {@link ProtectedMsgRQType }
     * 
     */
    public ProtectedMsgRQType createProtectedMsgRQType() {
        return new ProtectedMsgRQType();
    }

    /**
     * Create an instance of {@link ProtectedMsgServiceRequestType }
     * 
     */
    public ProtectedMsgServiceRequestType createProtectedMsgServiceRequestType() {
        return new ProtectedMsgServiceRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtectedMsgRQType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/bussines/services/protectedMsgService", name = "protectedMsgRQ")
    public JAXBElement<ProtectedMsgRQType> createProtectedMsgRQ(ProtectedMsgRQType value) {
        return new JAXBElement<ProtectedMsgRQType>(_ProtectedMsgRQ_QNAME, ProtectedMsgRQType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtectedMsgRSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nequi.co/message/bussines/services/protectedMsgService", name = "protectedMsgRS")
    public JAXBElement<ProtectedMsgRSType> createProtectedMsgRS(ProtectedMsgRSType value) {
        return new JAXBElement<ProtectedMsgRSType>(_ProtectedMsgRS_QNAME, ProtectedMsgRSType.class, null, value);
    }

}
