//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.27 at 09:49:14 AM COT 
//


package com.nequi.uts601.messaging.services.protectedmsg;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProtectedMsgServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProtectedMsgServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="protectedMsgRQ" type="{http://nequi.co/message/bussines/services/protectedMsgService}ProtectedMsgRQType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProtectedMsgServiceRequestType", propOrder = {
    "protectedMsgRQ"
})
public class ProtectedMsgServiceRequestType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected ProtectedMsgRQType protectedMsgRQ;

    /**
     * Gets the value of the protectedMsgRQ property.
     * 
     * @return
     *     possible object is
     *     {@link ProtectedMsgRQType }
     *     
     */
    public ProtectedMsgRQType getProtectedMsgRQ() {
        return protectedMsgRQ;
    }

    /**
     * Sets the value of the protectedMsgRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtectedMsgRQType }
     *     
     */
    public void setProtectedMsgRQ(ProtectedMsgRQType value) {
        this.protectedMsgRQ = value;
    }

}
