//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.27 at 09:49:57 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nequi.co/services/util/SecurityManager", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nequi.uts601.messaging.services.security;
